# Generated by Django 5.2.16 on 2026-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('safety_expert', 'کارشناس ایمنی'), ('health_expert', 'کارشناس بهداشت حرفه\u200cای'), ('environment_expert', 'کارشناس محیط زیست'), ('safety_supervisor', 'سرپرست ایمنی'), ('admin', 'مدیر سیستم')], default='safety_expert', max_length=20),
        ),
    ]
